### ISSUE TITLE
getChannel() is not a function????

### ISSUE THREAD

**Issue by zedxos** [Blackhawk-TA/dynoBot-Framework#24]
im testing the mention feature is not working and throws that error

**Comment by Blackhawk-TA** [comment]
The function getChannel was replaced by getTextChannel. 
The readme example was outdated. I've updated it.

**Comment by zedxos** [comment]
> The function getChannel was replaced by getTextChannel.
> The readme example was outdated. I've updated it.

Oh thankss im gonna use it now lol
